In [1]:
import pandas as pd
import numpy as np
import requests

In [ ]:
census_api_key = ''
variable = 'B01003_001E'
year = '2020'
url1 = 'https://api.census.gov/data/{0}/acs/acs5?get=NAME,{1}&for=us:*&key={2}'\
  .format(year, variable, census_api_key)
response = requests.request("GET", url1)
response.status_code

200

In [ ]:
response

In [ ]:
response.text

'[["NAME","B01003_001E","us"],\n["United States","326569308","1"]]'

In [ ]:
df_USA = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns={'B01001_001E' :'Cantidad de poblacion'})
df_USA

            NAME B01003_001E us
0  United States   326569308  1

In [ ]:
census_api_key = ''
variable = 'B01001_001E'
year = '2020'
# Data por estado
url2 = 'https://api.census.gov/data/{0}/acs/acs5?get=NAME,{1}&for=state:*&key={2}' .format(year, variable, census_api_key)
response = requests.request("GET", url2)
response.status_code

200

In [ ]:
df_estados = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns={'index': (0),'NAME': 'Estado','B01001_001E' :'Cantidad de habitantes', 'state' : 'Numero de Estado'})
df_estados

                  Estado Cantidad de habitantes Numero de Estado
0           Pennsylvania               12794885               42
1             California               39346023               06
2          West Virginia                1807426               54
3                   Utah                3151239               49
4               New York               19514849               36
5   District of Columbia                 701974               11
6                 Alaska                 736990               02
7                Florida               21216924               12
8         South Carolina                5091517               45
9           North Dakota                 760394               38
10                 Maine                1340825               23
11               Georgia               10516579               13
12               Alabama                4893186               01
13         New Hampshire                1355244               33
14                Oregon                4176346               41
15               Wyoming                 581348               56
16               Arizona                7174064               04
17             Louisiana                4664616               22
18               Indiana                6696893               18
19                 Idaho                1754367               16
20           Connecticut                3570549               09
21                Hawaii                1420074               15
22              Illinois               12716164               17
23         Massachusetts                6873003               25
24                 Texas               28635442               48
25               Montana                1061705               30
26              Nebraska                1923826               31
27                  Ohio               11675275               39
28              Colorado                5684926               08
29            New Jersey                8885418               34
30              Maryland                6037624               24
31              Virginia                8509358               51
32               Vermont                 624340               50
33        North Carolina               10386227               37
34              Arkansas                3011873               05
35            Washington                7512465               53
36                Kansas                2912619               20
37              Oklahoma                3949342               40
38             Wisconsin                5806975               55
39           Mississippi                2981835               28
40              Missouri                6124160               29
41              Michigan                9973907               26
42          Rhode Island                1057798               44
43             Minnesota                5600166               27
44                  Iowa                3150011               19
45            New Mexico                2097021               35
46                Nevada                3030281               32
47              Delaware                 967679               10
48           Puerto Rico                3255642               72
49              Kentucky                4461952               21
50          South Dakota                 879336               46
51             Tennessee                6772268               47

In [17]:
census_api_key = '75b955d8b4e06cf51293e4f4542213bfaa633986'
variable = 'C24070_011E'
year = '2020'
# Data por estado
url3 = 'https://api.census.gov/data/{0}/acs/acs5?get=NAME,{1}&for=state:*&key={2}' .format(year, variable, census_api_key)
response = requests.request("GET", url3)
response.status_code

200

In [18]:
response

In [19]:
response.text

'[["NAME","C24070_011E","state"],\n["Pennsylvania","1627281","42"],\n["California","3960265","06"],\n["West Virginia","207353","54"],\n["Utah","344198","49"],\n["New York","2673758","36"],\n["District of Columbia","69485","11"],\n["Alaska","83842","02"],\n["Florida","2039904","12"],\n["South Carolina","510174","45"],\n["North Dakota","104354","38"],\n["Maine","189240","23"],\n["Georgia","1025115","13"],\n["Alabama","480244","01"],\n["New Hampshire","180390","33"],\n["Oregon","470563","41"],\n["Wyoming","71989","56"],\n["Arizona","707882","04"],\n["Louisiana","496410","22"],\n["Indiana","750392","18"],\n["Idaho","182073","16"],\n["Connecticut","478318","09"],\n["Hawaii","143371","15"],\n["Illinois","1452209","17"],\n["Massachusetts","1019819","25"],\n["Texas","2932061","48"],\n["Montana","120662","30"],\n["Nebraska","245352","31"],\n["Ohio","1358326","39"],\n["Colorado","623737","08"],\n["New Jersey","1065323","34"],\n["Maryland","730263","24"],\n["Virginia","926211","51"],\n["Vermont","94190","50"],\n["North Carolina","1103440","37"],\n["Arkansas","321734","05"],\n["Washington","792288","53"],\n["Kansas","357098","20"],\n["Oklahoma","401780","40"],\n["Wisconsin","697836","55"],\n["Mississippi","316357","28"],\n["Missouri","705543","29"],\n["Michigan","1089747","26"],\n["Rhode Island","146465","44"],\n["Minnesota","753814","27"],\n["Iowa","391707","19"],\n["New Mexico","228325","35"],\n["Nevada","232486","32"],\n["Delaware","114152","10"],\n["Puerto Rico","236884","72"],\n["Kentucky","479978","21"],\n["South Dakota","107425","46"],\n["Tennessee","710151","47"]]'

In [16]:
df_transportepub = pd.DataFrame(response.json()[1:], columns=response.json()[0])
df_transportepub

                    NAME B08126_046E state
0           Pennsylvania      315578    42
1             California      843498    06
2          West Virginia        6085    54
3                   Utah       33830    49
4               New York     2418334    36
5   District of Columbia      119569    11
6                 Alaska        4247    02
7                Florida      154580    12
8         South Carolina       11723    45
9           North Dakota        2125    38
10                 Maine        3591    23
11               Georgia       93987    13
12               Alabama        6960    01
13         New Hampshire        5646    33
14                Oregon       79221    41
15               Wyoming        2812    56
16               Arizona       50759    04
17             Louisiana       21868    22
18               Indiana       27808    18
19                 Idaho        5142    16
20           Connecticut       77433    09
21                Hawaii       38177    15
22              Illinois      539825    17
23         Massachusetts      337729    25
24                 Texas      166825    48
25               Montana        3729    30
26              Nebraska        6256    31
27                  Ohio       79191    39
28              Colorado       82173    08
29            New Jersey      466091    34
30              Maryland      226646    24
31              Virginia      168784    51
32               Vermont        3877    50
33        North Carolina       46628    37
34              Arkansas        3950    05
35            Washington      218379    53
36                Kansas        6194    20
37              Oklahoma        6556    40
38             Wisconsin       44890    55
39           Mississippi        3335    28
40              Missouri       33546    29
41              Michigan       58641    26
42          Rhode Island       11747    44
43             Minnesota       93692    27
44                  Iowa       14278    19
45            New Mexico        8796    35
46                Nevada       41190    32
47              Delaware        9946    10
48           Puerto Rico       15077    72
49              Kentucky       18292    21
50          South Dakota        2046    46
51             Tennessee       18681    47